[package]
name = "fastnoise-lite-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
itertools = "0.11.0"
rayon = "1.8.0"
fastnoise-lite = { path = "../Rust" }
