[package]
name = "fastnoise-lite"
version = "1.0.2"
edition = "2021"
license = "MIT"
description = "FastNoiseLite Lite is an extremely portable open source noise generation library with a large selection of noise algorithms"
repository = "https://github.com/Auburn/FastNoiseLite"
readme = "README.md"
authors = ["Jordan Peck", "Keavon Chambers"]
categories = [
	"algorithms",
	"game-development",
	"graphics",
	"multimedia::images",
	"rendering",
]
keywords = [
	"noise",
	"fastnoise",
	"procedural",
	"simplex",
	"opensimplex",
	"cellular",
	"voronoi",
	"perlin",
	"value",
	"cubic",
	"fractal",
	"domain-warping",
	"2D",
	"3D",
	"heightmap",
	"terrain",
	"texture",
	"random",
	"generative",
]

[features]
f64 = []
